name: generate
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version, ex: div, v0.0.1'
        type: string
        required: false
        default: dev

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${{ inputs.releaseVersion }}
          mvn clean package

      - name: Summon
        run: |
          mkdir out
          cd target && cp bungeecordwhitelistct-${{ inputs.releaseVersion }}.jar ../out

      - uses: actions/upload-artifact@v4
        with:
          name: BungeeCordWhitelistCT-${{ inputs.releaseVersion }}.zip
          path: out
